before_script:
  - module add  python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath pytest-cov
  - module load  nextflow/0.31.0
  - ln -s /work/BICF/s163035/chipseq/*fastq.gz test_data/

stages:
  - unit
  - integration

user_configuration:
  stage: unit
  script:
  - pytest -m unit

single_end_mouse:
  stage: integration
  script:
  - nextflow run workflow/main.nf -resume
  - pytest -m singleend
  - pytest --cov=./workflow/scripts
  artifacts:
    expire_in: 2 days

paired_end_human:
  stage: integration
  script:
  - nextflow run workflow/main.nf --designFile "$CI_PROJECT_DIR/test_data/design_ENCSR729LGA_PE.txt" --genome 'GRCh38' --pairedEnd true -resume
  - pytest -m pairedend
  - pytest --cov=./workflow/scripts
  artifacts:
    expire_in: 2 days

single_end_diff:
  stage: integration
  script:
  - nextflow run workflow/main.nf --designFile "$CI_PROJECT_DIR/test_data/design_diff_SE.txt" --genome 'GRCm38' -resume
  - pytest -m pairedend
  - pytest --cov=./workflow/scripts
  artifacts:
    expire_in: 2 days

paired_end_diff:
  stage: integration
  script:
  - nextflow run workflow/main.nf --designFile "$CI_PROJECT_DIR/test_data/design_diff_PE.txt" --genome 'GRCh38' --pairedEnd true -resume
  - pytest -m pairedend
  - pytest --cov=./workflow/scripts
  artifacts:
    expire_in: 2 days
