variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule update --init --recursive
  - module add  python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath pytest-cov
  - module load nextflow/0.27.6
  - ln -s /project/shared/bicf_workflow_ref/workflow_testdata/chipseq/*fastq.gz test_data/



stages:
  - unit
  - integration

user_configuration:
  stage: unit
  script:
  - python workflow/process_scripts/setup.py install
  - pytest -m unit
  artifacts:
    expire_in: 2 days


single_end_mouse:
  stage: integration
  script:
  - nextflow run workflow/main.nf
  - pytest -m integration
  - pytest --cov=./workflow/scripts
  artifacts:
    expire_in: 2 days

paired_end_human:
  stage: integration
  script:
  - nextflow run workflow/main.nf --designFile "$CI_PROJECT_DIR/test_data/design_ENCSR729LGA_PE.txt" --genome 'GRCh38'
  artifacts:
    expire_in: 2 days
