before_script:
  - module add  python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath
  - module load nextflow/0.24.1-SNAPSHOT
  - ln -s /project/shared/bicf_workflow_ref/workflow_testdata/chipseq/*fastq.gz test_data/

stages:
  - unit
  - integration
  - acceptance

user_configuration:
  stage: unit
  script:
  - pytest -m unit

single_end_mouse:
  stage: integration
  script:
  - nextflow run workflow/main.nf

single_end_acceptance:
  stage: unit
  script:
  - pytest -m acceptance
