before_script:
  - module add  python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath pytest-cov
  - module load nextflow/0.31.0
  - ln -s /work/BICF/s163035/chipseq/*fastq.gz test_data/

stages:
  - unit
  - astrocyte
  - single
  - multiple

user_configuration:
  stage: unit
  script:
  - pytest -m unit
  - pytest -m unit --cov=./workflow/scripts

astrocyte:
  stage: astrocyte
  script:
  - module load astrocyte/0.1.0
  - module unload nextflow
  - cd ..
  - astrocyte_cli validate chipseq_analysis
  artifacts:
    expire_in: 2 days

single_end_mouse:
  stage: single
  script:
  - nextflow run workflow/main.nf -resume
  - pytest -m singleend
  artifacts:
    expire_in: 2 days

paired_end_human:
  stage: single
  script:
  - nextflow run workflow/main.nf --designFile "$CI_PROJECT_DIR/test_data/design_ENCSR729LGA_PE.txt" --genome 'GRCh38' --pairedEnd true -resume
  - pytest -m pairedend
  artifacts:
    expire_in: 2 days

single_end_diff:
  stage: multiple
  script:
  - nextflow run workflow/main.nf --designFile "$CI_PROJECT_DIR/test_data/design_diff_SE.txt" --genome 'GRCm38' -resume
  - pytest -m singlediff
  artifacts:
    expire_in: 2 days

paired_end_diff:
  stage: multiple
  script:
  - nextflow run workflow/main.nf --designFile "$CI_PROJECT_DIR/test_data/design_diff_PE.txt" --genome 'GRCh38' --pairedEnd true -resume
  - pytest -m paireddiff
  artifacts:
    expire_in: 2 days
